python -u run.py \
    --seed 1730272905 \
    --mode test \
    --data_path ./data/UCR \
    --data_name ABP \
    --n_vars 1 \
    --model_name Autoencoder \
    --data_embed local \
    --e_layer 2 \
    --n_heads 8 \
    --d_model 512 \
    --d_ff 1024 \
    --win_size 100 \
    --step_size 100 \
    --test_step_size 100 \
    --norm standard \
    --percentile 99.7 \
    --dropout 0.0 \
    --ckpt ckpt