python -u run.py \
    --seed 1729484836 \
    --mode test \
    --data_path ./data/UCR \
    --data_name Gait \
    --n_vars 1 \
    --model_name Autoencoder \
    --data_embed local \
    --e_layer 2 \
    --n_heads 8 \
    --d_model 256 \
    --d_ff 512 \
    --win_size 350 \
    --step_size 350 \
    --test_step_size 350 \
    --percentile 99.2 \
    --dropout 0.0 \
    --lr 5e-5 \
    --ckpt ckpt