python -u run.py \
    --seed 1728022774 \
    --mode test \
    --data_path ./data/GECCO \
    --data_name GECCO \
    --n_vars 9 \
    --model_name Autoencoder \
    --data_embed local \
    --e_layer 2 \
    --n_heads 8 \
    --d_model 128 \
    --d_ff 256 \
    --win_size 10 \
    --step_size 10 \
    --test_step_size 10 \
    --percentile 99.8 \
    --norm standard \
    --ckpt ckpt