python -u run.py \
    --seed 1730186808 \
    --mode test \
    --data_path ./data/UCR \
    --data_name PowerDemand \
    --n_vars 1 \
    --model_name Autoencoder \
    --data_embed local \
    --e_layer 3 \
    --n_heads 8 \
    --d_model 128 \
    --d_ff 256 \
    --win_size 100 \
    --step_size 100 \
    --test_step_size 100 \
    --percentile 99.8 \
    --norm standard \
    --ckpt ckpt