python -u run.py \
    --seed 1728363050 \
    --mode test \
    --data_path ./data/SWAN_SF \
    --data_name SWAN_SF \
    --n_vars 38 \
    --model_name Autoencoder \
    --data_embed local \
    --e_layer 2 \
    --n_heads 8 \
    --d_model 512 \
    --d_ff 1024 \
    --win_size 400 \
    --step_size 200 \
    --test_step_size 400 \
    --percentile 90.6 \
    --dropout 0.0 \
    --ckpt ckpt